ktor {
    deployment {
        port = 8081
    }
    application {
        modules = [ com.seamlis.ApplicationKt.module ]
    }
}

db {
    jdbcUrl = "jdbc:postgresql://localhost:5433/seamlis"
    jdbcUrl = ${?DB_JDBC_URL}
    user = "seamlis"
    user = ${?DB_USER}
    password = "seamlis_local_pass"
    password = ${?DB_PASSWORD}
    maxPoolSize = 10
}

jwt {
    secret = "super_secret_local_jwt_key_do_not_use_in_prod"
    secret = ${?JWT_SECRET}
    issuer = "http://0.0.0.0:8081/"
    audience = "http://localhost:3000/api"
    realm = "Seamlis API"
}

storage {
    endpoint = "http://localhost:9000"
    accessKey = "minioadmin"
    secretKey = "minioadmin"
    bucket = "seamlis-videos"
}
