ALTER TABLE videos ADD COLUMN view_count BIGINT NOT NULL DEFAULT 0;
ALTER TABLE videos ADD COLUMN like_count INT NOT NULL DEFAULT 0;
ALTER TABLE videos ADD COLUMN dislike_count INT NOT NULL DEFAULT 0;
ALTER TABLE videos ADD COLUMN comment_count INT NOT NULL DEFAULT 0;
